### ISSUE TITLE
Thonny IDE compatibility 

### ISSUE THREAD

**Issue by ajsb85** [ambiot/ambd_micropython#8]
REPL console error

```python
ERROR   thonny.plugins.micropython.backend: Crash in backend
Traceback (most recent call last):
  File "C:\Users\ajsb85\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\backend.py", line 136, in __init__
    self._prepare_after_soft_reboot(clean)
  File "C:\Users\ajsb85\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\backend.py", line 167, in _prepare_after_soft_reboot
    self._update_cwd()
  File "C:\Users\ajsb85\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\bare_metal_backend.py", line 402, in _update_cwd
    super()._update_cwd()
  File "C:\Users\ajsb85\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\backend.py", line 493, in _update_cwd
    self._cwd = self._evaluate("__thonny_helper.getcwd()")
  File "C:\Users\ajsb85\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\micropython\backend.py", line 611, in _evaluate
    raise ManagementError(script, out, err)
thonny.plugins.micropython.backend.ManagementError: Problem with a management command

SCRIPT:
__thonny_helper.print_mgmt_value(__thonny_helper.getcwd())

STDOUT:


STDERR:
Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File "<stdin>", line 44, in getcwd

AttributeError: 'module' object has no attribute 'getcwd'





Backend terminated or disconnected. Use 'Stop/Restart' to restart.

```

**Comment by xidameng** [comment]
Hi @ajsb85 
We will support one of many MicroPython IDEs, PyCraft is out of date and there is no update for quite a while, Thonny is a better choice out of all the IDEs as it comes with Raspberry Pi and had a active community, however, hardware-specific extension must be implemented before you can use Thonny for MicroPython, it will take a while

**Comment by 5t0n3r1pp3r** [comment]
this seems to be working now?

**Comment by S10143806H** [comment]
Hi @ajsb85 and @5t0n3r1pp3r ,

Thonny IDE is now supported.

Please follow the steps below for using Thonny IDE:
1.  Upload the MicroPython image into AmebaD
2.  Configure Com Port in Thonny
![image](https://user-images.githubusercontent.com/9852678/231098676-9b23c647-9665-474d-9fbd-633d8e549293.png)
3.  You can see the shell terminal upon the configuration is done, press the Reset button on the board, and you will see the MicroPython image working: 
![image](https://user-images.githubusercontent.com/9852678/231098923-768809fa-4030-49a8-b80f-7c6e9b138bc7.png)
4. Add Python Script in the text box on the top and press the Run (F5) Button to execute the code on your board.

If there is no further questions, I will proceed to close this issue.
Thank you.
